Algoritmo "antecessor e sucessor"

Var

    numero: inteiro
    antecessor: inteiro
    sucessor: inteiro



Inicio

      escreval("Digite um número inteiro: ")
      leia(numero)
      
      
       antecessor <- (numero - 1)
       sucessor <- (numero + 1)
       
       escreval("Antecessor: ", antecessor)
       escreval("Atual: ", numero)
       escreval("Sucessor: ", sucessor)


    
    
    

     
     


Fimalgoritmo