Algoritmo "As operações"


Var

   numero: real
   numeroDois: real
   resultado: real

Inicio

     escreval("Digite um número: ")
     leia(numero)
     escreva("Digite outro número: ")
     leia(numeroDois)
     resultado <- numero + numeroDois
     escreval(resultado)
     
     escreval("Digite um número: ")
     leia(numero)
     escreval("Digite outro número: ")
     leia(numeroDois)
     resultado <- numero - numeroDois
     escreval(resultado)
     
     escreval("Digite um número: ")
     leia(numero)
     escreva("Digite outro número: ")
     leia(numeroDois)
     resultado <- numero * numeroDois
     escreval(resultado)
     
     escreval("Digite um número: ")
     leia(numero)
     escreva("Digite outro número: ")
     leia(numeroDois)
     resultado <- numero / numeroDois
     escreval(resultado)
     
     

     
     
     
     




Fimalgoritmo