Algoritmo "Cartão de Visitas"

Var


Inicio

  escreval("*****************************************************")
  escreval("Nome: Pedro Henrique da Silva")
  escreval("E-mail principal: pedrohenriquedasilva200690@gmail.com")
  escreval("Email: pedro.h.silva984@aluno.senai.br")
  escreval("Telefone: 81 979165737")
  escreva("******************************************************")
     

     
     
     
     




Fimalgoritmo