Algoritmo "média de quatro notas"


Var

   primeiraNota: real
   segundaNota: real
   terceiraNota: real
   quartaNota: real
   resultado: real

Inicio

     escreval("Digite a primeira nota: ")
     leia(primeiraNota)
     escreval("Digite a segunda nota: ")
     leia(segundaNota)
     escreval("Digite a terceira nota: ")
     leia(terceiraNota)
     escreval("Digite a quarta nota: ")
     leia(quartaNota)

     resultado <- (primeiraNota + segundaNota + terceiraNota + quartaNota) / 3)
     escreva("A média é: ", resultado)
     


     
     
     




Fimalgoritmo