Algoritmo "média de três notas"


Var

   primeiraNota: real
   segundaNota: real
   terceiraNota: real
   resultado: real

Inicio

     escreval("Digite a primeira nota: ")
     leia(primeiraNota)
     escreval("Digite a segunda nota: ")
     leia(segundaNota)
     escreval("Digite a terceira nota: ")
     leia(terceiraNota)
     
     resultado <- (primeiraNota + segundaNota + terceiraNota) / 3)
     escreva("A média é: ", resultado)
     


     
     
     




Fimalgoritmo