Algoritmo "salário por hora"

Var

   horasTrabalhadas: real
   valorRecebido: real
   resultado: real



Inicio

     escreval("Digite a quantidade de horas trabalhadas: ")
     leia(horasTrabalhadas)
     escreval("Digite o valor recebido por hora: ")
     leia(valorRecebido)
     
     resultado <- (horasTrabalhadas * valorRecebido)
     
     escreval("Salário total: ", resultado)

    
    
    

     
     


Fimalgoritmo