Algoritmo "troca de valores"

Var

   valorA: inteiro
   valorB: inteiro
   valorInvertido: inteiro
   valorInvertidoDois: inteiro



Inicio

     escreval("Digite o valor de A: ")
     leia(valorA)
     escreval("Digite o valor de B: ")
     leia(valorB)
     
     valorInvertido <- valorB
     valorInvertidoDois <- valorA
     
     escreval(valorInvertido, " ", valorInvertidoDois)
     

    
    
    

     
     


Fimalgoritmo