Algoritmo "valor da compra"

Var

   precoUm: real
   precoDois: real
   precoTres: real
   total: real



Inicio

    escreval("Digite o preço do primeiro produto: ")
    leia(precoUm)
    escreval("Digite o preço do segundo produto: ")
    leia(precoDois)
    escreval("Digite o preço do terceiro produto: ")
    leia(precoTres)
    
    total <- (precoUm + precoDois + precoTres)
    escreva("Total da compra: ", total)
    
    
    

     
     


Fimalgoritmo